services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9100:3000"
    environment:
      - DATABASE_URL=postgresql://linkpay:linkpay_secret@postgres:5432/linkpay
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-linkpay-dev-secret-change-in-production-12345}
      - NEXTAUTH_URL=http://localhost:9100
      - AUTH_TRUST_HOST=true
      - AAMARPAY_STORE_ID=${AAMARPAY_STORE_ID:-aamarpay-store-id}
      - AAMARPAY_KEY=${AAMARPAY_KEY:-aamarpay-api-key}
      - AAMARPAY_URL=${AAMARPAY_URL:-https://sandbox.aamarpay.com}
      - AAMARPAY_SIGNATURE_KEY=${AAMARPAY_SIGNATURE_KEY:-aamarpay-signature-key}
      - BKASH_USERNAME=${BKASH_USERNAME:-your_bkash_username}
      - BKASH_PASSWORD=${BKASH_PASSWORD:-your_bkash_password}
      - BKASH_APP_KEY=${BKASH_APP_KEY:-your_bkash_app_key}
      - BKASH_APP_SECRET=${BKASH_APP_SECRET:-your_bkash_app_secret}
      - BKASH_URL=${BKASH_URL:-https://tokenized.sandbox.bka.sh/v1.2.0-beta}
      - RESEND_API_KEY=${RESEND_API_KEY:-re_your_resend_api_key}
      - NEXT_PUBLIC_APP_URL=http://localhost:9100
      - ADMIN_EMAILS=admin@linkpay.com,zohirrayhanweb@gmail.com,admin@linkpaybd.com
      - SSLCOMMERZ_STORE_ID=${SSLCOMMERZ_STORE_ID:-neege6997413bb22cd}
      - SSLCOMMERZ_STORE_PASSWORD=${SSLCOMMERZ_STORE_PASSWORD:-neege6997413bb22cd@ssl}
      - SSLCOMMERZ_URL=${SSLCOMMERZ_URL:-https://sandbox.sslcommerz.com}
      - UPLOAD_DIR=/app/data/uploads
    volumes:
      - uploads_data:/app/data/uploads
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - linkpay-network

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=linkpay
      - POSTGRES_PASSWORD=linkpay_secret
      - POSTGRES_DB=linkpay
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "9101:5432"
    restart: unless-stopped
    networks:
      - linkpay-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U linkpay"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "9102:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - linkpay-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    ports:
      - "9103:9000"
      - "9104:9001"
    environment:
      - MINIO_ROOT_USER=linkpay
      - MINIO_ROOT_PASSWORD=linkpay_secret
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - linkpay-network

volumes:
  postgres_data:
  redis_data:
  minio_data:
  uploads_data:

networks:
  linkpay-network:
    driver: bridge
